version: '3.2'

services:
  ocr-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/bin/sh", "-c", "air run main.go"]
    volumes:
      - ./src:/usr/app/src
    ports:
      - 3000:3000
      